### ISSUE TITLE
"Error: Forbidden" when Cotoami Scraper to Docker

### ISSUE THREAD

**Issue by moviefuns** [cotoami/cotoami#155]
Hello. Thanks for your cotoami project!
I've deployed cotoami docker using the script https://raw.githubusercontent.com/cotoami/cotoami/master/launch/run.sh .
Everything works but cotoami scraper. When it sends links or selections, the chrome addon pop up error msg "Error: Forbidden". 
Is there anything I can do to fix that?

**Comment by marubinotto** [comment]
@moviefuns I've just released a new version to fix this issue. Could you try it again to see if it works now?

**Comment by moviefuns** [comment]
Thanks.
Seems the problem caused by the domain name, as default by 'localhost'. I changed it to my domain name in docker-compose.yml. Works by now.
Thank you for the great work!

**Comment by kroschu** [comment]
Have the same problem. My docker-compose.yml :

```
version: '2'
services:

  cotoami:
    image: cotoami/cotoami:latest
    ports:
      - "443:4000"
    links:
      - redis
      - postgres
      - neo4j
    environment:
      SECRET_KEY_BASE: iirr+1hGL0ew7N/jQmnQ2crnwBBwjHWPkM/QZk7tmD8/ARQhvAH4j69wh1WHH7gv
      COTOAMI_URL_SCHEME: https
      COTOAMI_URL_HOST: km.uabp.ml
      COTOAMI_REDIS_HOST: redis
      COTOAMI_REPO_USER: postgres
      COTOAMI_REPO_PASSWORD: postgres
      COTOAMI_REPO_DATABASE: cotoami
      COTOAMI_REPO_HOST: postgres
      COTOAMI_NEO4J_HOST: neo4j
      COTOAMI_EMAIL_FROM: no-reply@cotoa.me
      COTOAMI_ADDITIONAL_VALID_ORIGINS: chrome-extension://
      COTOAMI_SMTP_SERVER: smtp.gmail.com 
      COTOAMI_SMTP_PORT: "587"
      COTOAMI_URL_PORT: "443"
      COTOAMI_SMTP_USER: tukroschu@gmail.com
      COTOAMI_SMTP_PASSWORD: ****************
      COTOAMI_EMAIL_FROM: tukroschu@gmail.com
      COTOAMI_OWNER_EMAILS: tukroschu@gmail.com
      
  redis:
    image: redis:alpine

  postgres:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cotoami
    volumes:
      - postgres-data:/var/lib/postgresql/data

  neo4j:
    image: neo4j:3.2.2
    environment:
      NEO4J_AUTH: none
    volumes:
      - neo4j-data:/data 
 

volumes:
  postgres-data:
  neo4j-data:
```
Please tell me what I need to fix.
